class DvdRes:
    def __init__(self):
        self.productImage = ""
        self.detailPageImage = ""
        self.title = ""
        self.originalPrice = ""
        self.discountPrice = ""
        self.sold = "X"
        self.castMember = ""
        self.director = ""
        self.screenRatio = ""
        self.sound = ""
        self.subtitle = ""
        self.productionDistribution = ""
        self.regionCode = ""
        self.rating = ""
        self.runningTime = ""
        self.media = ""
        self.details = ""
